PR For Template folder, Writing Tests, Continuous Integration
rozenborg/test-simulations-mgmt-repo pull request #41
Opened 2017-02-22 12:14 UTC by andela-iamao

### What does this PR do?

This PR contains outputs for UI template folder, writing tests and continuous integration 

### Description of Task to be completed?

Task delivers : 
-  proposed front-end of project,
- All tests required by the project
- Successful Travis CI build of development branch 

### How should this be manually tested?

- To view the template, Open your terminal and type:
```
git clone https://github.com/andela-iamao/inverted-index.git
```
-- Navigate to `template` folder and open index.html with browser of your choice 

 -To run tests, Open your terminal and type the following:
```
git clone https://github.com/andela-iamao/inverted-index.git
cd inverted-index
npm install
npm test
```
### Any background context you want to provide?

N/A

### What are the relevant pivotal tracker stories?

- Create UI template
- Set up testing environment
- Set up Travis CI
- Write required tests

### Screenshots

#### Screenshot for UI template
![Landing page view](https://github.com/andela-iamao/inverted-index/blob/feature/139624267/ui-template-dev/template/img/template1.png?raw=true "Landing page view")
[Landing page view](https://github.com/andela-iamao/inverted-index/blob/feature/139624267/ui-template-dev/template/img/template1.png?raw=true)

![View on uploadt](https://github.com/andela-iamao/inverted-index/blob/feature/139624267/ui-template-dev/template/img/template2.png?raw=true "view on upload")
[View on upload](https://github.com/andela-iamao/inverted-index/blob/feature/139624267/ui-template-dev/template/img/template2.png?raw=true)

![Generated index view](https://github.com/andela-iamao/inverted-index/blob/feature/139624267/ui-template-dev/template/img/template3.png?raw=true "Generated index view")
[Generated index view](https://github.com/andela-iamao/inverted-index/blob/feature/139624267/ui-template-dev/template/img/template3.png?raw=true)

![About inverted index view](https://github.com/andela-iamao/inverted-index/blob/feature/139624267/ui-template-dev/template/img/template4.png?raw=true "About inverted index view")
[About inverted index view](https://github.com/andela-iamao/inverted-index/blob/feature/139624267/ui-template-dev/template/img/template4.png?raw=true)

![Search view](https://github.com/andela-iamao/inverted-index/blob/feature/139624267/ui-template-dev/template/img/template5.png?raw=true "Search view")
[Search view](https://github.com/andela-iamao/inverted-index/blob/feature/139624267/ui-template-dev/template/img/template5.png?raw=true)

#### Successful Travis CI Build
![Travis build of development branch](https://cloud.githubusercontent.com/assets/25608320/23211104/460a7a38-f8f8-11e6-918a-111e7d43c9cd.png)

2017-02-25 23:12 UTC, q-ode reviewed
I'll be expecting the PR for your tests.

2017-02-25 23:12 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-html-js-css-outputs-(template)/output/README.md
> +#### Output
Great UI!

You might want to rethink having a `Create Index` button per file. What happens when we have 50 files uploaded?

2017-02-25 23:12 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/README.md
> +- [test](https://github.com/andela-iamao/inverted-index/blob/feature/140182663/tests-dev/dist/js/components/index-table/index-table.component.spec.js)
This isn't a PR, I can't effectively comment on the issues.

2017-02-27 16:21 UTC, andela-iamao commented
UI changes fixed

2017-03-01 15:18 UTC, q-ode requested changes
Please go through your Welcome to Simulations email again you'll find that there're clear instructions to guide you on code style guidelines.

Please get acquainted with them.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/setting-up-continuous-integration-(build-server)/output/README.md
> +- [andela-iamao/inverted-index/development](https://github.com/andela-iamao/inverted-index/tree/development)
Nice one!

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +
Let's ensure to stick to the ES6 standard of writing classes and their methods.

```
class InvertedIndex {
  methodName() {
  }
}
```

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +  const sortedIndex = sort(index);
Where is the `sort` method declared. Is it in another class?

Why isn't it imported?

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> + * function should generate index when a valid json file is passesd in
Typo: `passesd`

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +      (book.title.constructor === String && book.text.constructor === String))));
This line is more than 80 characters.

Also `typeof` is recommended for check variable types. Example:
```
const booleanObject = new Boolean(false);  
booleanObject.constructor === Boolean // => true

const booleanPrimitive = false;  
booleanPrimitive.constructor === Boolean // => true
```

You can consult this [article](https://rainsoft.io/understanding-constructor-property/) for more information.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> + * @param {any} data
Why is the datatype `any`?

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +    this.generated_index = {};
You never used this in this class.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +    this.fetchTitle = fetchTitle;
Same as the `sort` function.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> + * @param {any} data
Why is this parameter `any`? and what does `data` mean?

Let's endeavour to use descriptive names for variables.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +  if (data === undefined || data === null) return null;
What happened to braces? Let's include it please.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +  if (!this.isValid(data)) return null;
I feel like your `isValid` function should handle what you're trying to on line 8 and 9.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +    const text = book.text.replace(/[^a-zA-Z ]/g, '').toLowerCase().split(' ');
What are you trying to achieve here? I feel like you can put this in a function that would explicitly say what you're trying to do with all of this: `replace(/[^a-zA-Z ]/g, '').toLowerCase().split(' ')`

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +  const index = {};
I'd have a black line between this and line 12. Logical code blocks aids code readability.

Also, apply this in all areas.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +  const sortedIndex = sort(index);
The variable `sortedIndex` is redundant. You declared it only to return the value in the next line.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +  const queryArray = query.replace(/[^A-Za-z ]/g, '').toLowerCase().split(' ');
According to [Andela Code Style Guides](https://github.com/andela/code-review-guidelines/tree/master/coding-style-guides) we try to avoid object types in variable names. So `queryArray` is cancelled :-).

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +  queryArray.forEach((q) => {
Please what is `q`? #DescriptiveVariableNames

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +function searchAll(query, dataset) {
What is `dataset`, why is it `any`?

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +    // fetchTitle is found in helpers.js
If you imported is you'll not need this comment.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +function isValid(data) {
I feel this function can be written in a readable way. There's too much going on and it's all muddled together.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +}
From the look of things this class actually never stores any of the indices created.

How do you preserve the indices that have been created earlier? I hope you're not planning to do that outside this class?

Kindly ensure that class methods manage the class's state.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/helpers.js
> + * @returns sorted object
No return type.

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/helpers.js
> +/**
Plix... Plix... and Plix... let's steer away from using writing functions like this :-) 

This file can be better written as:
```
const indexHelper = {
  sort(data) {
    ...
  }
}
```

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/helpers.js
> + * @param {any} data
Is `data` an array?

Why is does your JSDoc say `any`?

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/helpers.js
> +  const title = data.map(item => item.title);
`title` is redundant.

This entire function could be written as `return data.map(item => item.title)`

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/helpers.js
> + * @returns an array if data
Typo: `@returns an array if data` I'm sure you meant `of`

2017-03-01 15:18 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/inverted-index.spec.js
> +
You've got a barrage of style violations in this file.

Please fix before I even take a look.

2017-03-02 22:20 UTC, q-ode reviewed
Great Job!

I don't see you testing for search terms that don't exist though. Let's implement that.

Also, I don't see you testing your helper functions. Let's have tests that cover those too.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/helpers.js
> +   * @returns an array if data
No datatype specified for your return.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/helpers.js
> +   * @returns boolean
You're missing braces for your return type, also would help to have a description.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/helpers.js
> +   * @returns {String}
You're missing a return description.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/helpers.js
> +  stripStr(str) {
`stripStr` doesn't communicate much, please be more descriptive.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/helpers.js
> +}
Line 45 is missing a semicolon.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/helpers.js
> +module.exports = helpers;
Violation of [eol-last](https://github.com/eslint/eslint/blob/master/docs/rules/eol-last.md) AirBnB Style Guide

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +   * @returns {Object} result - in key value pair where each word in the query is key and value is an  array of titles
You realize there's an 80 character per line limit right?

Kindly ensure you clean this up all through this file.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +  isValid(data) {
This function can be either made static or moved to a `json-helper` of some sort as it does not modify any of the members of this class.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +                 && typeof book.text === 'string'){
What you have here is a bunch of trailing spaces and not indents. Please check you IDE settings if you need to.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +    return (valid.indexOf(false) === -1);
Nice one simplifying this.

PS: The extra bracket isn't necessary sha...lol :simple_smile:

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +    if (!data || !Array.isArray(data)|| data.length < 1) {
I expect that you have a space between `!Array.isArray(data)` and  `||`.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +  generateIndex(fileName, data) {
I don't subscribe to the parameter named `data` I'm sure we can find something more descriptive.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +          const wordArray = index[word];
We typically avoid using data types in variable names.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +    data.map((book) => {
I'm guessing you're calling `.map` because you want to loop through every element in the data array. Why did you go this route?

You now had to hack the eslint violation by returning null in line 61. 👀 

Is there a better way to go about this?

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +        } else if(word !== '') {
I'm not sure I like this idea: `else if(word !== '')`

Will `word` ever be an empty string? Seems it's an element in the `text` array which was created from a split using ` ` of text.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +
Line 67 has a trailing space. Kindly address this across board.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +    const queryArray = helpers.stripStr(query).split(' ');
Variable naming of `queryArray`.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +      if (words.indexOf(word) !== -1 && word !== ' ') {
You already split `query` into `queryArray` using ` `, will there ever be a word in it with just ` `?

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/inverted-index.spec.js
> +const InvertedIndex = require('../js/inverted-index');
Looks much better now.

You have trailing spaces in a lot of places, please fix them.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/inverted-index.spec.js
> +  describe('Should test for the instance of InvertedIndexTest', () => {
Your test suites are not named properly.

I should be able to read your suites and your specs and make somewhat of a proper sentence out of it.
```
'Should test for the instance of InvertedIndexTest'
  Should return true if InvertedIndexTest is an instance of Object
```
The above doesn't exactly make a sentence. Feel free to research more on Behaviour-Driven Development.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/inverted-index.spec.js
> +      expect(InvertedIndexTest.isValid(model.fake_data)).toBe(false);
I like that you have a model where you store data for tests, I'd like to see you use better names for these objects.
For example, the spec on line 32 is testing for `invalid json data` but the model being uses is named `fake_data`. It'll help to have descriptive names.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/inverted-index.spec.js
> +      toEqual(model.searchResults[0]);
Style Violation on lines 89 - 90: [dot-location](http://eslint.org/docs/rules/dot-location)

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/inverted-index.spec.js
> +  const InvertedIndexTest = new InvertedIndex();
Use camelCase when naming objects [naming conventions](https://github.com/airbnb/javascript#naming--camelCase)

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/inverted-index.spec.js
> +      expect(InvertedIndexTest.search(model.searchQueries[0], 'test1')).
Do you really need to declare `searchQueries` and `searchResults` as arrays? There's only one of each in your helper.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/inverted-index.spec.js
> +      expect(InvertedIndexTest.search(model.searchQueries[0], 'test1')).
What is `test1`? #VariableNaming

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/testmodels.js
> +class FakeInvertedIndex {
The file is poorly indented, please fix.

2017-03-02 22:20 UTC, q-ode commented on 06-building-a-program-start-to-finish/solving-the-problem/output/inverted-index.js
> +const helpers = require('./helpers');
According to AirBnB your file name should match their default export. i.e `InvertedIndex.js`

2017-03-07 17:17 UTC, andela-iamao commented
Issues have been addressed

2017-03-09 18:35 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/inverted-index.spec.js
> +
Nice one fixing the errors. However, your suites and specs do not follow BDD guidelines.

Your suites when combined with your specs should make a proper sentence.

You currently have: `Test suite for helper functions`...`Given an unordered object, function should return an alphabetically ordered version of the object`

I'd probably refactor this as:

`Sort function`...`should return an alphabetically ordered version of the object`

PS: With this you'll not have all these lines exceeding 80 characters.

Please re-write, I also don't see you testing for the exact index that was created and also for the exact search results returned for one file and then when you search through all files.

2017-03-10 15:13 UTC, andela-iamao commented
@q-ode Thank you. I've made the changes to the suites and spec

2017-03-13 16:40 UTC, q-ode reviewed
Great Job!

2017-03-13 16:40 UTC, q-ode commented on 06-building-a-program-start-to-finish/checking-repository-health/output/README.md
> +- [development branch](https://github.com/andela-iamao/inverted-index)
Nice!

2017-03-13 16:40 UTC, q-ode commented on 06-building-a-program-start-to-finish/reflecting-on-the-learning-experience/output/README.md
> +- [Medium Blog Post](https://medium.com/@ashamao90/so-far-so-good-655ddd552fbb)
Haha! 50 comments, let's hope I have none in this PR.

2017-03-13 16:40 UTC, q-ode commented on 06-building-a-program-start-to-finish/delivering-your-product/output/README.md
> +- [Release notes](https://docs.google.com/a/andela.com/document/d/1bEepMNpR1INDcd7bHVYaR-tYgyRbMnk6Dj9ALCpdsSM/edit?usp=sharing)
Looks good!

2017-03-13 16:40 UTC, q-ode commented on 06-building-a-program-start-to-finish/setting-up-software-development-environments-(deployment)/output/README.md
> +- [Production App](https://i-invertedindex.herokuapp.com/)
Good one!

2017-03-13 16:40 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/inverted-index.spec.js
> +const InvertedIndexTest = new InvertedIndex();
You can still write your specs like this without exceeding 80 characters:
```
it('should return false if nothing is passed in', () => {
    expect(helpers.isValid()).toBe(false);
  });
```

2017-03-13 16:40 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/inverted-index.spec.js
> +});
Looks good!

2017-03-13 16:40 UTC, q-ode commented on 06-building-a-program-start-to-finish/writing-tests/output/testmodels.js
> +class FakeInvertedIndex {
Still poorly indented.

2017-03-13 16:41 UTC, q-ode approved these changes

2017-03-13 16:41 UTC, merged